### ISSUE TITLE
No Single Page Mode Available For Landscape Image

### ISSUE THREAD

**Issue by shubhamhirve** [yogeshpaliyal/Android-Curl-View-Animation#1]
I have landscape image which is not displayed correctly. Please add function to make it single view.

**Comment by yogeshpaliyal** [comment]
i don't understand your problem

**Comment by yogeshpaliyal** [comment]
please elaborate, and provide me the screenshot if you have

**Comment by yogeshpaliyal** [comment]
use this 	
``` Gradle
compile 'com.github.yogeshpaliyal:Android-Curl-View-Animation:91ff803da5'
```
and in xml file CurlView add 
``` Xml
 app:horizontal_two_page="false"
```

**Comment by shubhamhirve** [comment]
how can we scale images? how can we set them to fitcenter or fitxy mode?
